# Generated by Django 4.0.6 on 2022-07-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bday', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('hobby', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('address', models.TextField()),
            ],
        ),
    ]
